# Generated by Django 3.2.12 on 2025-02-08 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
